### ISSUE TITLE
Nice extension!

### ISSUE THREAD

**Issue by pawamoy** [jonghwanhyeon/griffe-modernized-annotations#1]
Hi @jonghwanhyeon, congrats, the extension is super clean! It's fun to see that you have managed to implement our built-in expression modernization in an extension :smile: I will reference it in our docs :slightly_smiling_face:

**Comment by pawamoy** [comment]
Oh by the way, you might want to add a `griffe-extension` topic to the GitHub repository, for discoverability :smile:

**Comment by jonghwanhyeon** [comment]
I created this extension because I needed its functionality for personal use. If it has caused any discomfort, I will unpublish it.

**Comment by jonghwanhyeon** [comment]
I apologize if this has caused any discomfort, and I will unpublish the package.
